spring.application.name=exam_qr

spring.datasource.url=jdbc:postgresql://pg-e40d0f1-exam-qr.l.aivencloud.com:12238/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_qmQRr_W8zNciwpMeNXQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuncaygurban@gmail.com
spring.mail.password=bmvphmiozgfwxjtc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true